[package]
name = "rocksdb-memory-usage"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytesize = "2.0.1"
clap = { version = "4.0", features = ["derive"] }
rocksdb = { version = "0.42.1", package = "rust-rocksdb" }
sysinfo = "0.30"
tempdir = "0.3.7"
